-- Create a custom type for knowledge levels
create type public.knowledge_level as enum (
  'Explorador/Amador/Iniciante',
  'Coffee Lover',
  'Coffee Lover Pro',
  'Barista',
  'Mestre Cafeeiro'
);

-- CLIENTS Table
-- Stores customer information.
create table public.clients (
  id uuid not null default gen_random_uuid() primary key,
  created_at timestamp with time zone not null default now(),
  name text not null,
  email text null unique,
  phone text null,
  address text null,
  birthday date null,
  knowledge_level public.knowledge_level null,
  source_channel text null
);
-- Add comments to the table and columns
comment on table public.clients is 'Stores detailed information about each client.';
comment on column public.clients.knowledge_level is 'Client''s self-assessed coffee knowledge level.';
comment on column public.clients.source_channel is 'The channel through which the client was first acquired (e.g., Loja Física, Site, Instagram).';
-- Enable Row Level Security
alter table public.clients enable row level security;


-- INTERACTIONS Table
-- Records every touchpoint with a client across all channels.
create table public.interactions (
  id bigint generated by default as identity primary key,
  created_at timestamp with time zone not null default now(),
  client_id uuid not null references public.clients(id) on delete cascade,
  channel text not null,
  type text not null,
  details text null,
  value numeric(10, 2) null
);
-- Add comments
comment on table public.interactions is 'Logs each interaction with a client, such as purchases, inquiries, etc.';
comment on column public.interactions.channel is 'The channel of the interaction (e.g., Loja Física, WhatsApp, Site).';
comment on column public.interactions.type is 'The type of interaction (e.g., Compra, Dúvida, Cadastro).';
comment on column public.interactions.value is 'The monetary value associated with the interaction, if any (e.g., purchase amount).';
-- Enable Row Level Security
alter table public.interactions enable row level security;


-- TAGS Table
-- Stores tags that can be applied to clients for segmentation.
create table public.tags (
  id bigint generated by default as identity primary key,
  name text not null unique,
  created_at timestamp with time zone not null default now()
);
-- Add comments
comment on table public.tags is 'Defines a list of tags for segmenting clients (e.g., Cliente Fiel, Aluno Avançado).';
-- Enable Row Level Security
alter table public.tags enable row level security;


-- CLIENT_TAGS Junction Table
-- Links clients to tags in a many-to-many relationship.
create table public.client_tags (
  client_id uuid not null references public.clients(id) on delete cascade,
  tag_id bigint not null references public.tags(id) on delete cascade,
  primary key (client_id, tag_id)
);
-- Add comments
comment on table public.client_tags is 'Junction table to associate clients with multiple tags.';
-- Enable Row Level Security
alter table public.client_tags enable row level security;
